name: tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    container: ocaml/opam:ubuntu-20.04-ocaml-4.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Install some package
        run: opam install batteries
